apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mpc.name }}
  labels:
    name: {{ .Values.mpc.name }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.mpc.name }}

