imagePullSecret: regcred
mpc:
  image:
    repository: ghcr.io/cosset-io/cosset-mpc/mpc
    pullPolicy: Always
    tag: latest
  name: cosset-mpc
  enabled: true
  replicas: 1
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: mpc.cosset.cf
    tls:
      enabled: true
      secret: mpc.cosset.cf
  env:
    - name: DATABASE_URL
      value: postgresql://mpc:password@mpc-db-postgresql/mpc
